name: Publish to crates.io

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Publish candle-metal-kernels-mold
        run: cargo publish --manifest-path candle-metal-kernels/Cargo.toml --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Wait for crates.io index
        run: sleep 30

      - name: Publish candle-core-mold
        run: cargo publish --manifest-path candle-core/Cargo.toml --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Wait for crates.io index
        run: sleep 30

      - name: Publish candle-nn-mold
        run: cargo publish -p candle-nn-mold --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Wait for crates.io index
        run: sleep 30

      - name: Publish candle-transformers-mold
        run: cargo publish -p candle-transformers-mold --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
